### PR TITLE
Split weight into mass and force, and add area.

### PR DESCRIPTION
**Pull request by thejpster**
Also adds macros to add fundamental physics equations in a simpler fashion (impl_maths!).

### CODE REVIEW

**Comment by thejpster** [comment]
Humm. I got a bit carried away today. Take either one of these PRs, and I'll rebase the other one to suit.

**Comment by thejpster** [comment]
Any objections to this one @jocull? It's a bit big I'm afraid - I've had time on my hands.

**Comment by jocull** [comment]
@thejpster There is a ton of work here! I'm gonna take your word for it, you're mostly in charge of this now 😉 

Thanks for the commits!

**Comment by jocull** [comment]
@thejpster The README should really be updated to reflect all of the new stuff -- it's still referencing `0.3.0`

**Comment by jocull** [comment]
It'd make sense to publish out to Cargo after that also I think 👍

**Pull request merged**
